package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table HNITEM.
 */
public class HNItem {

    private String title;
    private String by;
    private Integer id;
    private String kids;
    private Integer score;
    private String time;
    private String type;
    private String url;

    public HNItem() {
    }

    public HNItem(Integer id) {
        this.id = id;
    }

    public HNItem(String title, String by, Integer id, String kids, Integer score, String time, String type, String url) {
        this.title = title;
        this.by = by;
        this.id = id;
        this.kids = kids;
        this.score = score;
        this.time = time;
        this.type = type;
        this.url = url;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getBy() {
        return by;
    }

    public void setBy(String by) {
        this.by = by;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getKids() {
        return kids;
    }

    public void setKids(String kids) {
        this.kids = kids;
    }

    public Integer getScore() {
        return score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

}
